from YJKPYI.APIData import *
from typing import Any
class Hi_AddToAndReadYjk:
    def ReflectAndCreateYDB(self, updateInfo: Hi_UpdateInfo, path: str, name: str) -> bool: ...
    def ReflectDataAndDef(self, updateInfo: Hi_UpdateInfo) -> None: ...
    def ReadFromYJK(self) -> Hi_DbModelData: ...
    def ReadBzcAndProj(self) -> None: ...
    def ReadIdByNO(self, kind: GjKind, gjNO: int, flrNO: int) -> int: ...
    def ReadYdb(self, path: str) -> Hi_DbModelData: ...
    def GetDbmodel(self) -> Hi_DbModelData: ...
    def SetDbmodel(self, db: Hi_DbModelData) -> None: ...
    def GetMaxID(self) -> int: ...
    def CreateYDB(self, path: str, name: str) -> bool: ...
    def IPC_ToYJK(self) -> bool: ...
    def IPC_YJKToUs(self) -> bool: ...
    def GetUnionID(self) -> int: ...
    def ReflecToYJK(self, updateInfo: Hi_UpdateInfo) -> bool: ...
    def RefreshToYJK(self) -> bool: ...
    def RestCadInfo(self) -> None: ...
class ShapeVals:
    k: int
    b: int
    h: int
    u: int
    t: int
    d: int
    f: int
    l: int
    m: int
    p: int