# coding: utf-8

"""
    WeGlide

    Quantifying airsports

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from weglide_client.api.competition_api import CompetitionApi


class TestCompetitionApi(unittest.TestCase):
    """CompetitionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CompetitionApi()

    def tearDown(self) -> None:
        pass

    def test_delete_competition_v1_competition_competition_id_delete(self) -> None:
        """Test case for delete_competition_v1_competition_competition_id_delete

        Delete Competition
        """
        pass

    def test_get_competition_v1_competition_competition_id_get(self) -> None:
        """Test case for get_competition_v1_competition_competition_id_get

        Get Competition
        """
        pass

    def test_get_running_competition_v1_competition_get(self) -> None:
        """Test case for get_running_competition_v1_competition_get

        Get Running Competition
        """
        pass

    def test_post_competition_logo_v1_competition_logo_post(self) -> None:
        """Test case for post_competition_logo_v1_competition_logo_post

        Post Competition Logo
        """
        pass

    def test_post_competition_v1_competition_post(self) -> None:
        """Test case for post_competition_v1_competition_post

        Post Competition
        """
        pass

    def test_post_task_v1_competition_task_post(self) -> None:
        """Test case for post_task_v1_competition_task_post

        Post Task
        """
        pass


if __name__ == '__main__':
    unittest.main()
