# coding: utf-8

"""
    WeGlide

    Quantifying airsports

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from weglide_client.api.flightdata_api import FlightdataApi


class TestFlightdataApi(unittest.TestCase):
    """FlightdataApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FlightdataApi()

    def tearDown(self) -> None:
        pass

    def test_get_flightdata_v1_flightdata_flight_id_get(self) -> None:
        """Test case for get_flightdata_v1_flightdata_flight_id_get

        Get Flightdata
        """
        pass


if __name__ == '__main__':
    unittest.main()
