# coding: utf-8

"""
    WeGlide

    Quantifying airsports

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from weglide_client.models.copilot_status import CopilotStatus

class TestCopilotStatus(unittest.TestCase):
    """CopilotStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCopilotStatus(self):
        """Test CopilotStatus"""
        # inst = CopilotStatus()

if __name__ == '__main__':
    unittest.main()
