# coding: utf-8

"""
    WeGlide

    Quantifying airsports

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from weglide_client.api.waypointcollection_api import WaypointcollectionApi


class TestWaypointcollectionApi(unittest.TestCase):
    """WaypointcollectionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WaypointcollectionApi()

    def tearDown(self) -> None:
        pass

    def test_delete_waypoint_collection_v1_waypointcollection_collection_id_delete(self) -> None:
        """Test case for delete_waypoint_collection_v1_waypointcollection_collection_id_delete

        Delete Waypoint Collection
        """
        pass

    def test_get_waypoint_collection_list_v1_waypointcollection_get(self) -> None:
        """Test case for get_waypoint_collection_list_v1_waypointcollection_get

        Get Waypoint Collection List
        """
        pass

    def test_get_waypoint_collection_v1_waypointcollection_collection_id_get(self) -> None:
        """Test case for get_waypoint_collection_v1_waypointcollection_collection_id_get

        Get Waypoint Collection
        """
        pass

    def test_patch_waypoint_collection_v1_waypointcollection_collection_id_patch(self) -> None:
        """Test case for patch_waypoint_collection_v1_waypointcollection_collection_id_patch

        Patch Waypoint Collection
        """
        pass

    def test_post_waypoint_collection_v1_waypointcollection_post(self) -> None:
        """Test case for post_waypoint_collection_v1_waypointcollection_post

        Post Waypoint Collection
        """
        pass


if __name__ == '__main__':
    unittest.main()
