# coding: utf-8

"""
    Curia Platform API

    These are the docs for the curia platform API. To test, generate an authorization token first.  # noqa: E501

    OpenAPI spec version: 3.2.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AnalysisJobOutput(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'data': 'object',
        'analysis_job_id': 'str',
        'analysis_job': 'AnalysisJob',
        'last_updated_by': 'str',
        'created_by': 'str',
        'created_at': 'datetime',
        'updated_at': 'datetime',
        'archived_at': 'datetime',
        'version': 'float'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'data': 'data',
        'analysis_job_id': 'analysisJobId',
        'analysis_job': 'analysisJob',
        'last_updated_by': 'lastUpdatedBy',
        'created_by': 'createdBy',
        'created_at': 'createdAt',
        'updated_at': 'updatedAt',
        'archived_at': 'archivedAt',
        'version': 'version'
    }

    def __init__(self, id=None, name=None, data=None, analysis_job_id=None, analysis_job=None, last_updated_by=None, created_by=None, created_at=None, updated_at=None, archived_at=None, version=None):  # noqa: E501
        """AnalysisJobOutput - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._data = None
        self._analysis_job_id = None
        self._analysis_job = None
        self._last_updated_by = None
        self._created_by = None
        self._created_at = None
        self._updated_at = None
        self._archived_at = None
        self._version = None
        self.discriminator = None
        self.id = id
        self.name = name
        self.data = data
        self.analysis_job_id = analysis_job_id
        self.analysis_job = analysis_job
        self.last_updated_by = last_updated_by
        self.created_by = created_by
        self.created_at = created_at
        self.updated_at = updated_at
        if archived_at is not None:
            self.archived_at = archived_at
        self.version = version

    @property
    def id(self):
        """Gets the id of this AnalysisJobOutput.  # noqa: E501


        :return: The id of this AnalysisJobOutput.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this AnalysisJobOutput.


        :param id: The id of this AnalysisJobOutput.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this AnalysisJobOutput.  # noqa: E501


        :return: The name of this AnalysisJobOutput.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AnalysisJobOutput.


        :param name: The name of this AnalysisJobOutput.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def data(self):
        """Gets the data of this AnalysisJobOutput.  # noqa: E501


        :return: The data of this AnalysisJobOutput.  # noqa: E501
        :rtype: object
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this AnalysisJobOutput.


        :param data: The data of this AnalysisJobOutput.  # noqa: E501
        :type: object
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")  # noqa: E501

        self._data = data

    @property
    def analysis_job_id(self):
        """Gets the analysis_job_id of this AnalysisJobOutput.  # noqa: E501


        :return: The analysis_job_id of this AnalysisJobOutput.  # noqa: E501
        :rtype: str
        """
        return self._analysis_job_id

    @analysis_job_id.setter
    def analysis_job_id(self, analysis_job_id):
        """Sets the analysis_job_id of this AnalysisJobOutput.


        :param analysis_job_id: The analysis_job_id of this AnalysisJobOutput.  # noqa: E501
        :type: str
        """
        if analysis_job_id is None:
            raise ValueError("Invalid value for `analysis_job_id`, must not be `None`")  # noqa: E501

        self._analysis_job_id = analysis_job_id

    @property
    def analysis_job(self):
        """Gets the analysis_job of this AnalysisJobOutput.  # noqa: E501


        :return: The analysis_job of this AnalysisJobOutput.  # noqa: E501
        :rtype: AnalysisJob
        """
        return self._analysis_job

    @analysis_job.setter
    def analysis_job(self, analysis_job):
        """Sets the analysis_job of this AnalysisJobOutput.


        :param analysis_job: The analysis_job of this AnalysisJobOutput.  # noqa: E501
        :type: AnalysisJob
        """
        if analysis_job is None:
            raise ValueError("Invalid value for `analysis_job`, must not be `None`")  # noqa: E501

        self._analysis_job = analysis_job

    @property
    def last_updated_by(self):
        """Gets the last_updated_by of this AnalysisJobOutput.  # noqa: E501


        :return: The last_updated_by of this AnalysisJobOutput.  # noqa: E501
        :rtype: str
        """
        return self._last_updated_by

    @last_updated_by.setter
    def last_updated_by(self, last_updated_by):
        """Sets the last_updated_by of this AnalysisJobOutput.


        :param last_updated_by: The last_updated_by of this AnalysisJobOutput.  # noqa: E501
        :type: str
        """
        if last_updated_by is None:
            raise ValueError("Invalid value for `last_updated_by`, must not be `None`")  # noqa: E501

        self._last_updated_by = last_updated_by

    @property
    def created_by(self):
        """Gets the created_by of this AnalysisJobOutput.  # noqa: E501


        :return: The created_by of this AnalysisJobOutput.  # noqa: E501
        :rtype: str
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by):
        """Sets the created_by of this AnalysisJobOutput.


        :param created_by: The created_by of this AnalysisJobOutput.  # noqa: E501
        :type: str
        """
        if created_by is None:
            raise ValueError("Invalid value for `created_by`, must not be `None`")  # noqa: E501

        self._created_by = created_by

    @property
    def created_at(self):
        """Gets the created_at of this AnalysisJobOutput.  # noqa: E501


        :return: The created_at of this AnalysisJobOutput.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this AnalysisJobOutput.


        :param created_at: The created_at of this AnalysisJobOutput.  # noqa: E501
        :type: datetime
        """
        if created_at is None:
            raise ValueError("Invalid value for `created_at`, must not be `None`")  # noqa: E501

        self._created_at = created_at

    @property
    def updated_at(self):
        """Gets the updated_at of this AnalysisJobOutput.  # noqa: E501


        :return: The updated_at of this AnalysisJobOutput.  # noqa: E501
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this AnalysisJobOutput.


        :param updated_at: The updated_at of this AnalysisJobOutput.  # noqa: E501
        :type: datetime
        """
        if updated_at is None:
            raise ValueError("Invalid value for `updated_at`, must not be `None`")  # noqa: E501

        self._updated_at = updated_at

    @property
    def archived_at(self):
        """Gets the archived_at of this AnalysisJobOutput.  # noqa: E501


        :return: The archived_at of this AnalysisJobOutput.  # noqa: E501
        :rtype: datetime
        """
        return self._archived_at

    @archived_at.setter
    def archived_at(self, archived_at):
        """Sets the archived_at of this AnalysisJobOutput.


        :param archived_at: The archived_at of this AnalysisJobOutput.  # noqa: E501
        :type: datetime
        """

        self._archived_at = archived_at

    @property
    def version(self):
        """Gets the version of this AnalysisJobOutput.  # noqa: E501


        :return: The version of this AnalysisJobOutput.  # noqa: E501
        :rtype: float
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this AnalysisJobOutput.


        :param version: The version of this AnalysisJobOutput.  # noqa: E501
        :type: float
        """
        if version is None:
            raise ValueError("Invalid value for `version`, must not be `None`")  # noqa: E501

        self._version = version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AnalysisJobOutput, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AnalysisJobOutput):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
