# coding: utf-8

"""
    Curia Platform API

    These are the docs for the curia platform API. To test, generate an authorization token first.  # noqa: E501

    OpenAPI spec version: 3.16.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ModelPopulationJoinedCohortDefinitionJoinedPeriodDefinitionResponseDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'type': 'str',
        'start_date': 'datetime',
        'end_date': 'datetime',
        'created_at': 'datetime',
        'created_by': 'str',
        'updated_at': 'datetime',
        'archived_at': 'datetime',
        'last_updated_by': 'str',
        'version': 'float'
    }

    attribute_map = {
        'id': 'id',
        'type': 'type',
        'start_date': 'startDate',
        'end_date': 'endDate',
        'created_at': 'createdAt',
        'created_by': 'createdBy',
        'updated_at': 'updatedAt',
        'archived_at': 'archivedAt',
        'last_updated_by': 'lastUpdatedBy',
        'version': 'version'
    }

    def __init__(self, id=None, type=None, start_date=None, end_date=None, created_at=None, created_by=None, updated_at=None, archived_at=None, last_updated_by=None, version=None):  # noqa: E501
        """ModelPopulationJoinedCohortDefinitionJoinedPeriodDefinitionResponseDto - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._type = None
        self._start_date = None
        self._end_date = None
        self._created_at = None
        self._created_by = None
        self._updated_at = None
        self._archived_at = None
        self._last_updated_by = None
        self._version = None
        self.discriminator = None
        if id is not None:
            self.id = id
        self.type = type
        self.start_date = start_date
        self.end_date = end_date
        if created_at is not None:
            self.created_at = created_at
        if created_by is not None:
            self.created_by = created_by
        if updated_at is not None:
            self.updated_at = updated_at
        if archived_at is not None:
            self.archived_at = archived_at
        if last_updated_by is not None:
            self.last_updated_by = last_updated_by
        if version is not None:
            self.version = version

    @property
    def id(self):
        """Gets the id of this ModelPopulationJoinedCohortDefinitionJoinedPeriodDefinitionResponseDto.  # noqa: E501


        :return: The id of this ModelPopulationJoinedCohortDefinitionJoinedPeriodDefinitionResponseDto.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ModelPopulationJoinedCohortDefinitionJoinedPeriodDefinitionResponseDto.


        :param id: The id of this ModelPopulationJoinedCohortDefinitionJoinedPeriodDefinitionResponseDto.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def type(self):
        """Gets the type of this ModelPopulationJoinedCohortDefinitionJoinedPeriodDefinitionResponseDto.  # noqa: E501


        :return: The type of this ModelPopulationJoinedCohortDefinitionJoinedPeriodDefinitionResponseDto.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ModelPopulationJoinedCohortDefinitionJoinedPeriodDefinitionResponseDto.


        :param type: The type of this ModelPopulationJoinedCohortDefinitionJoinedPeriodDefinitionResponseDto.  # noqa: E501
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501
        allowed_values = ["evidence", "data_delay", "intervention", "pre_outcome_delay", "outcome", "diagnosis_gaps_validation", "diagnosis_gaps_follow_up", "data delay", "pre-outcome delay"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def start_date(self):
        """Gets the start_date of this ModelPopulationJoinedCohortDefinitionJoinedPeriodDefinitionResponseDto.  # noqa: E501


        :return: The start_date of this ModelPopulationJoinedCohortDefinitionJoinedPeriodDefinitionResponseDto.  # noqa: E501
        :rtype: datetime
        """
        return self._start_date

    @start_date.setter
    def start_date(self, start_date):
        """Sets the start_date of this ModelPopulationJoinedCohortDefinitionJoinedPeriodDefinitionResponseDto.


        :param start_date: The start_date of this ModelPopulationJoinedCohortDefinitionJoinedPeriodDefinitionResponseDto.  # noqa: E501
        :type: datetime
        """
        if start_date is None:
            raise ValueError("Invalid value for `start_date`, must not be `None`")  # noqa: E501

        self._start_date = start_date

    @property
    def end_date(self):
        """Gets the end_date of this ModelPopulationJoinedCohortDefinitionJoinedPeriodDefinitionResponseDto.  # noqa: E501


        :return: The end_date of this ModelPopulationJoinedCohortDefinitionJoinedPeriodDefinitionResponseDto.  # noqa: E501
        :rtype: datetime
        """
        return self._end_date

    @end_date.setter
    def end_date(self, end_date):
        """Sets the end_date of this ModelPopulationJoinedCohortDefinitionJoinedPeriodDefinitionResponseDto.


        :param end_date: The end_date of this ModelPopulationJoinedCohortDefinitionJoinedPeriodDefinitionResponseDto.  # noqa: E501
        :type: datetime
        """
        if end_date is None:
            raise ValueError("Invalid value for `end_date`, must not be `None`")  # noqa: E501

        self._end_date = end_date

    @property
    def created_at(self):
        """Gets the created_at of this ModelPopulationJoinedCohortDefinitionJoinedPeriodDefinitionResponseDto.  # noqa: E501


        :return: The created_at of this ModelPopulationJoinedCohortDefinitionJoinedPeriodDefinitionResponseDto.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this ModelPopulationJoinedCohortDefinitionJoinedPeriodDefinitionResponseDto.


        :param created_at: The created_at of this ModelPopulationJoinedCohortDefinitionJoinedPeriodDefinitionResponseDto.  # noqa: E501
        :type: datetime
        """

        self._created_at = created_at

    @property
    def created_by(self):
        """Gets the created_by of this ModelPopulationJoinedCohortDefinitionJoinedPeriodDefinitionResponseDto.  # noqa: E501


        :return: The created_by of this ModelPopulationJoinedCohortDefinitionJoinedPeriodDefinitionResponseDto.  # noqa: E501
        :rtype: str
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by):
        """Sets the created_by of this ModelPopulationJoinedCohortDefinitionJoinedPeriodDefinitionResponseDto.


        :param created_by: The created_by of this ModelPopulationJoinedCohortDefinitionJoinedPeriodDefinitionResponseDto.  # noqa: E501
        :type: str
        """

        self._created_by = created_by

    @property
    def updated_at(self):
        """Gets the updated_at of this ModelPopulationJoinedCohortDefinitionJoinedPeriodDefinitionResponseDto.  # noqa: E501


        :return: The updated_at of this ModelPopulationJoinedCohortDefinitionJoinedPeriodDefinitionResponseDto.  # noqa: E501
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this ModelPopulationJoinedCohortDefinitionJoinedPeriodDefinitionResponseDto.


        :param updated_at: The updated_at of this ModelPopulationJoinedCohortDefinitionJoinedPeriodDefinitionResponseDto.  # noqa: E501
        :type: datetime
        """

        self._updated_at = updated_at

    @property
    def archived_at(self):
        """Gets the archived_at of this ModelPopulationJoinedCohortDefinitionJoinedPeriodDefinitionResponseDto.  # noqa: E501


        :return: The archived_at of this ModelPopulationJoinedCohortDefinitionJoinedPeriodDefinitionResponseDto.  # noqa: E501
        :rtype: datetime
        """
        return self._archived_at

    @archived_at.setter
    def archived_at(self, archived_at):
        """Sets the archived_at of this ModelPopulationJoinedCohortDefinitionJoinedPeriodDefinitionResponseDto.


        :param archived_at: The archived_at of this ModelPopulationJoinedCohortDefinitionJoinedPeriodDefinitionResponseDto.  # noqa: E501
        :type: datetime
        """

        self._archived_at = archived_at

    @property
    def last_updated_by(self):
        """Gets the last_updated_by of this ModelPopulationJoinedCohortDefinitionJoinedPeriodDefinitionResponseDto.  # noqa: E501


        :return: The last_updated_by of this ModelPopulationJoinedCohortDefinitionJoinedPeriodDefinitionResponseDto.  # noqa: E501
        :rtype: str
        """
        return self._last_updated_by

    @last_updated_by.setter
    def last_updated_by(self, last_updated_by):
        """Sets the last_updated_by of this ModelPopulationJoinedCohortDefinitionJoinedPeriodDefinitionResponseDto.


        :param last_updated_by: The last_updated_by of this ModelPopulationJoinedCohortDefinitionJoinedPeriodDefinitionResponseDto.  # noqa: E501
        :type: str
        """

        self._last_updated_by = last_updated_by

    @property
    def version(self):
        """Gets the version of this ModelPopulationJoinedCohortDefinitionJoinedPeriodDefinitionResponseDto.  # noqa: E501


        :return: The version of this ModelPopulationJoinedCohortDefinitionJoinedPeriodDefinitionResponseDto.  # noqa: E501
        :rtype: float
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this ModelPopulationJoinedCohortDefinitionJoinedPeriodDefinitionResponseDto.


        :param version: The version of this ModelPopulationJoinedCohortDefinitionJoinedPeriodDefinitionResponseDto.  # noqa: E501
        :type: float
        """

        self._version = version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ModelPopulationJoinedCohortDefinitionJoinedPeriodDefinitionResponseDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ModelPopulationJoinedCohortDefinitionJoinedPeriodDefinitionResponseDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
