# Generated by Django 4.0.8 on 2023-02-03 14:53

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locatechar',
            name='cache_expiry',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0)),
        ),
    ]
