# Autogenerated by devscripts/update-version.py

__version__ = '2025.03.30.232927'

RELEASE_GIT_HEAD = 'f033d86b96b36f8c5289dd7c3304f42d4d9f6ff4'

VARIANT = 'pip'

UPDATE_HINT = 'You installed yt-dlp with pip or using the wheel from PyPi; Use that to update'

CHANNEL = 'nightly'

ORIGIN = 'yt-dlp/yt-dlp-nightly-builds'

_pkg_version = '2025.03.30.232927dev'
