# coding: utf-8

# flake8: noqa
"""
    WeGlide

    Quantifying airsports

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from weglide_client.models.achievement import Achievement
from weglide_client.models.achievement_with_badge import AchievementWithBadge
from weglide_client.models.achievement_with_badge_no_user import AchievementWithBadgeNoUser
from weglide_client.models.aircraft import Aircraft
from weglide_client.models.aircraft_base import AircraftBase
from weglide_client.models.aircraft_device import AircraftDevice
from weglide_client.models.aircraft_flight import AircraftFlight
from weglide_client.models.aircraft_list import AircraftList
from weglide_client.models.airport import Airport
from weglide_client.models.airport_base import AirportBase
from weglide_client.models.airport_flight import AirportFlight
from weglide_client.models.airspace_violation import AirspaceViolation
from weglide_client.models.app_schemas_task_score_task_flight import AppSchemasTaskScoreTaskFlight
from weglide_client.models.app_schemas_task_task_flight import AppSchemasTaskTaskFlight
from weglide_client.models.badge import Badge
from weglide_client.models.body_reset_password_v1_auth_reset_password_post import BodyResetPasswordV1AuthResetPasswordPost
from weglide_client.models.captcha import Captcha
from weglide_client.models.club import Club
from weglide_client.models.club_flight import ClubFlight
from weglide_client.models.collection_format import CollectionFormat
from weglide_client.models.competition_class_in import CompetitionClassIn
from weglide_client.models.competition_device_in import CompetitionDeviceIn
from weglide_client.models.competition_in import CompetitionIn
from weglide_client.models.competition_task_in import CompetitionTaskIn
from weglide_client.models.contest import Contest
from weglide_client.models.contest_name import ContestName
from weglide_client.models.contest_order import ContestOrder
from weglide_client.models.copilot_status import CopilotStatus
from weglide_client.models.declaration_in import DeclarationIn
from weglide_client.models.device import Device
from weglide_client.models.device_post import DevicePost
from weglide_client.models.filter import Filter
from weglide_client.models.flight_collection import FlightCollection
from weglide_client.models.flight_collection_create import FlightCollectionCreate
from weglide_client.models.flight_collection_order import FlightCollectionOrder
from weglide_client.models.flight_collection_update import FlightCollectionUpdate
from weglide_client.models.flight_comment import FlightComment
from weglide_client.models.flight_comment_create import FlightCommentCreate
from weglide_client.models.flight_comment_reaction import FlightCommentReaction
from weglide_client.models.flight_comment_reaction_create import FlightCommentReactionCreate
from weglide_client.models.flight_contest import FlightContest
from weglide_client.models.flight_detail import FlightDetail
from weglide_client.models.flight_order import FlightOrder
from weglide_client.models.flight_rank_list import FlightRankList
from weglide_client.models.flight_star_order import FlightStarOrder
from weglide_client.models.flight_update import FlightUpdate
from weglide_client.models.gender import Gender
from weglide_client.models.geo_json_point import GeoJSONPoint
from weglide_client.models.geom_value import GeomValue
from weglide_client.models.http_validation_error import HTTPValidationError
from weglide_client.models.igc_file import IGCFile
from weglide_client.models.igc_file_flight import IGCFileFlight
from weglide_client.models.id import Id
from weglide_client.models.key import Key
from weglide_client.models.list_contest_name import ListContestName
from weglide_client.models.msg import Msg
from weglide_client.models.o_auth2_client_api import OAuth2ClientAPI
from weglide_client.models.order_by import OrderBy
from weglide_client.models.properties import Properties
from weglide_client.models.push_subscription import PushSubscription
from weglide_client.models.query import Query
from weglide_client.models.ranking import Ranking
from weglide_client.models.ranking_category import RankingCategory
from weglide_client.models.ranking_contest import RankingContest
from weglide_client.models.ranking_order import RankingOrder
from weglide_client.models.ranking_scoring_class import RankingScoringClass
from weglide_client.models.ranking_user import RankingUser
from weglide_client.models.request_update_email import RequestUpdateEmail
from weglide_client.models.rule_set import RuleSet
from weglide_client.models.score_kind import ScoreKind
from weglide_client.models.search_query import SearchQuery
from weglide_client.models.search_query_documents_inner import SearchQueryDocumentsInner
from weglide_client.models.segment_flight import SegmentFlight
from weglide_client.models.segment_format import SegmentFormat
from weglide_client.models.segment_score_flight import SegmentScoreFlight
from weglide_client.models.story import Story
from weglide_client.models.story_geom_value import StoryGeomValue
from weglide_client.models.story_update import StoryUpdate
from weglide_client.models.task import Task
from weglide_client.models.task_create import TaskCreate
from weglide_client.models.task_kind import TaskKind
from weglide_client.models.task_order import TaskOrder
from weglide_client.models.task_score_flight import TaskScoreFlight
from weglide_client.models.task_score_order import TaskScoreOrder
from weglide_client.models.task_update import TaskUpdate
from weglide_client.models.task_user import TaskUser
from weglide_client.models.travel import Travel
from weglide_client.models.travel_update import TravelUpdate
from weglide_client.models.turnpoint_feature import TurnpointFeature
from weglide_client.models.turnpoint_kind import TurnpointKind
from weglide_client.models.unit import Unit
from weglide_client.models.user import User
from weglide_client.models.user_create import UserCreate
from weglide_client.models.user_delete import UserDelete
from weglide_client.models.user_flight_detail import UserFlightDetail
from weglide_client.models.user_group_create import UserGroupCreate
from weglide_client.models.user_group_order import UserGroupOrder
from weglide_client.models.user_group_simple import UserGroupSimple
from weglide_client.models.user_group_update import UserGroupUpdate
from weglide_client.models.user_in_db import UserInDB
from weglide_client.models.user_message import UserMessage
from weglide_client.models.user_update import UserUpdate
from weglide_client.models.user_with_image import UserWithImage
from weglide_client.models.user_with_image_and_copilot import UserWithImageAndCopilot
from weglide_client.models.validation_error import ValidationError
from weglide_client.models.validation_error_loc_inner import ValidationErrorLocInner
from weglide_client.models.waypoint_collection import WaypointCollection
from weglide_client.models.waypoint_collection_create import WaypointCollectionCreate
from weglide_client.models.waypoint_collection_order import WaypointCollectionOrder
from weglide_client.models.waypoint_collection_update import WaypointCollectionUpdate
from weglide_client.models.waypoint_create import WaypointCreate
