# coding: utf-8

"""
    WeGlide

    Quantifying airsports

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from weglide_client.api.flight_star_api import FlightStarApi


class TestFlightStarApi(unittest.TestCase):
    """FlightStarApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FlightStarApi()

    def tearDown(self) -> None:
        pass

    def test_delete_flight_star_v1_flightdetail_star_flight_id_delete(self) -> None:
        """Test case for delete_flight_star_v1_flightdetail_star_flight_id_delete

        Delete Flight Star
        """
        pass

    def test_get_flight_star_v1_flightdetail_star_flight_id_get(self) -> None:
        """Test case for get_flight_star_v1_flightdetail_star_flight_id_get

        Get Flight Star
        """
        pass

    def test_post_flight_star_v1_flightdetail_star_flight_id_post(self) -> None:
        """Test case for post_flight_star_v1_flightdetail_star_flight_id_post

        Post Flight Star
        """
        pass


if __name__ == '__main__':
    unittest.main()
