# coding: utf-8

"""
    WeGlide

    Quantifying airsports

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from weglide_client.models.story import Story

class TestStory(unittest.TestCase):
    """Story unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Story:
        """Test Story
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Story`
        """
        model = Story()
        if include_optional:
            return Story(
                id = 56,
                user_id = 56,
                flight_id = 56,
                image = '',
                comment = '',
                start_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                end_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                distance = 1.337,
                geom = {
                    'key' : null
                    },
                alt = 56,
                ground_speed = 56,
                vario = 1.337,
                bearing = 56,
                time_offset = 56,
                youtube_id = '',
                width = 56,
                height = 56,
                video_url = '',
                video_status = '',
                video_duration = 1.337
            )
        else:
            return Story(
                id = 56,
                user_id = 56,
                flight_id = 56,
                time_offset = 56,
                width = 56,
                height = 56,
        )
        """

    def testStory(self):
        """Test Story"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
