# coding: utf-8

"""
    WeGlide

    Quantifying airsports

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from weglide_client.models.task import Task

class TestTask(unittest.TestCase):
    """Task unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Task:
        """Test Task
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Task`
        """
        model = Task()
        if include_optional:
            return Task(
                id = 56,
                name = '',
                kind = '',
                penalized_distance = 1.337,
                min_distance = 1.337,
                max_distance = 1.337,
                start_on_leg = True,
                closed = True,
                bbox = [
                    1.337
                    ],
                stars = 56,
                from_igcfile = True,
                user = weglide_client.models.task_user.TaskUser(
                    id = 56, 
                    name = '', ),
                ruleset = 'D',
                private = True,
                point_features = [
                    null
                    ],
                description = '',
                locked = True,
                token = '',
                created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                modified = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                scoring_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                scoring_airport = weglide_client.models.airport_base.AirportBase(
                    id = 56, 
                    name = '', 
                    region = '', ),
                user_group = weglide_client.models.user_group_simple.UserGroupSimple(
                    id = 56, 
                    name = '', 
                    image = '', ),
                min_time = 56,
                start_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return Task(
                id = 56,
                kind = '',
                penalized_distance = 1.337,
                start_on_leg = True,
                closed = True,
                bbox = [
                    1.337
                    ],
                stars = 56,
                from_igcfile = True,
                private = True,
                point_features = [
                    null
                    ],
                locked = True,
                created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testTask(self):
        """Test Task"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
