# coding: utf-8

"""
    Curia Platform API

    These are the docs for the curia platform API. To test, generate an authorization token first.  # noqa: E501

    OpenAPI spec version: 1.21.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import curia.api.curia.api.curia.api.curia.api.swagger_client
from curia.api.curia.api.curia.api.curia.api.swagger_client.models.cohort_definition import CohortDefinition  # noqa: E501
from curia.api.curia.api.curia.api.curia.api.swagger_client.rest import ApiException


class TestCohortDefinition(unittest.TestCase):
    """CohortDefinition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCohortDefinition(self):
        """Test CohortDefinition"""
        # FIXME: construct object with mandatory attributes with example values
        # model = curia.api.curia.api.curia.api.swagger_client.models.cohort_definition.CohortDefinition()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
