# Form implementation generated from reading ui file '/tmp/tmp9tig2kmi/jdsimpleautostart-1.5/jdSimpleAutostart/ui/AddMenuDialog.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddMenuDialog(object):
    def setupUi(self, AddMenuDialog):
        AddMenuDialog.setObjectName("AddMenuDialog")
        AddMenuDialog.resize(573, 497)
        self.verticalLayout = QtWidgets.QVBoxLayout(AddMenuDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=AddMenuDialog)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.category_list = QtWidgets.QListWidget(parent=AddMenuDialog)
        self.category_list.setObjectName("category_list")
        self.horizontalLayout.addWidget(self.category_list)
        self.entry_list = QtWidgets.QListWidget(parent=AddMenuDialog)
        self.entry_list.setObjectName("entry_list")
        self.horizontalLayout.addWidget(self.entry_list)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.button_box = QtWidgets.QDialogButtonBox(parent=AddMenuDialog)
        self.button_box.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.button_box.setObjectName("button_box")
        self.verticalLayout.addWidget(self.button_box)

        self.retranslateUi(AddMenuDialog)
        self.button_box.accepted.connect(AddMenuDialog.accept) # type: ignore
        self.button_box.rejected.connect(AddMenuDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AddMenuDialog)

    def retranslateUi(self, AddMenuDialog):
        _translate = QtCore.QCoreApplication.translate
        AddMenuDialog.setWindowTitle(_translate("AddMenuDialog", "Add from Menu"))
        self.label.setText(_translate("AddMenuDialog", "You can add Programs from your Menu to your Autostart"))
