__title__ = 'cpnpy'
__description__ = 'A Python-based library designed to simulate Colored Petri Nets (CPNs) with optional time semantics.'
__url__ = 'https://github.com/fit-alessandro-berti/cpn-py'
__version__ = '0.2.1'
__author__ = 'Alessandro Berti'
__author_email__ = 'a.berti@pads.rwth-aachen.de'
__license__ = 'GPL-3.0'
