__title__ = "HRegex"
__description__ = "HRegex designed to simplify regex creation"
__url__ = "https://github.com/farhaanaliii/hregex"
__version__ = "1.0.0"
__author__ = "Farhan Ali"
__author_email__ = "i.farhanali.dev@gmail.com"
__license__ = "Apache 2.0"
__copyright__ = "Copyright Farhan Ali"
