# Generated by Django 4.2.6 on 2023-11-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0003_triginvasion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solarsystemconnection',
            old_name='prefer_less_safe',
            new_name='p_less_safe',
        ),
        migrations.RenameField(
            model_name='solarsystemconnection',
            old_name='prefer_shortest',
            new_name='p_shortest',
        ),
        migrations.RenameField(
            model_name='solarsystemconnection',
            old_name='prefer_safest',
            new_name='p_safest',
        ),
    ]
