# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: testbot/contrib/base/resources/protoc/tv_audio.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'testbot/contrib/base/resources/protoc/tv_audio.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from testbot.contrib.base.resources.protoc import basic_type_pb2 as testbot_dot_contrib_dot_base_dot_resources_dot_protoc_dot_basic__type__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4testbot/contrib/base/resources/protoc/tv_audio.proto\x12%testbot.contrib.base.resources.protoc\x1a\x36testbot/contrib/base/resources/protoc/basic_type.proto2\xf3\x01\n\rSettingsAudio\x12p\n\x0esetAudioOption\x12..testbot.contrib.base.resources.protoc.IntType\x1a,.testbot.contrib.base.resources.protoc.Empty\"\x00\x12p\n\x0egetAudioOption\x12,.testbot.contrib.base.resources.protoc.Empty\x1a..testbot.contrib.base.resources.protoc.IntType\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'testbot.contrib.base.resources.protoc.tv_audio_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SETTINGSAUDIO']._serialized_start=152
  _globals['_SETTINGSAUDIO']._serialized_end=395
# @@protoc_insertion_point(module_scope)
