# Generated by Django 4.0 on 2023-10-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunting', '0003_alter_agent_character_alter_agent_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locatechar',
            name='locate_char_agent',
            field=models.ManyToManyField(blank=True, to='hunting.LocateCharAgent', verbose_name='Valid Locator Agents'),
        ),
        migrations.AlterField(
            model_name='target',
            name='alts',
            field=models.ManyToManyField(blank=True, to='hunting.TargetAlt', verbose_name='Alts'),
        ),
    ]
