
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-03-27T10:59:12-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "7cf8231978d64d3788b0ddccdea334111039213f",
 "version": "2025.3.27"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
