# coding: utf-8

"""
    WeGlide

    Quantifying airsports

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Union
from typing import Optional, Set
from typing_extensions import Self

class AirspaceViolation(BaseModel):
    """
    AirspaceViolation
    """ # noqa: E501
    id: StrictInt
    violation: StrictBool
    airspace_openaip_id: StrictStr
    airspace_style: StrictStr
    airspace_name: StrictStr
    airspace_max_alt: StrictInt
    airspace_min_alt: StrictInt
    intervals: List[datetime]
    display_intervals: List[datetime]
    total_seconds: Union[StrictFloat, StrictInt]
    __properties: ClassVar[List[str]] = ["id", "violation", "airspace_openaip_id", "airspace_style", "airspace_name", "airspace_max_alt", "airspace_min_alt", "intervals", "display_intervals", "total_seconds"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AirspaceViolation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AirspaceViolation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "violation": obj.get("violation"),
            "airspace_openaip_id": obj.get("airspace_openaip_id"),
            "airspace_style": obj.get("airspace_style"),
            "airspace_name": obj.get("airspace_name"),
            "airspace_max_alt": obj.get("airspace_max_alt"),
            "airspace_min_alt": obj.get("airspace_min_alt"),
            "intervals": obj.get("intervals"),
            "display_intervals": obj.get("display_intervals"),
            "total_seconds": obj.get("total_seconds")
        })
        return _obj


