# coding: utf-8

"""
    WeGlide

    Quantifying airsports

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from weglide_client.api.user_group_api import UserGroupApi


class TestUserGroupApi(unittest.TestCase):
    """UserGroupApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserGroupApi()

    def tearDown(self) -> None:
        pass

    def test_add_user_v1_usergroup_add_user_group_id_post(self) -> None:
        """Test case for add_user_v1_usergroup_add_user_group_id_post

        Add User
        """
        pass

    def test_delete_user_group_pic_v1_usergroup_image_user_group_id_delete(self) -> None:
        """Test case for delete_user_group_pic_v1_usergroup_image_user_group_id_delete

        Delete User Group Pic
        """
        pass

    def test_delete_user_group_v1_usergroup_user_group_id_delete(self) -> None:
        """Test case for delete_user_group_v1_usergroup_user_group_id_delete

        Delete User Group
        """
        pass

    def test_delete_user_v1_usergroup_add_user_group_id_delete(self) -> None:
        """Test case for delete_user_v1_usergroup_add_user_group_id_delete

        Delete User
        """
        pass

    def test_get_user_group_v1_usergroup_user_group_id_get(self) -> None:
        """Test case for get_user_group_v1_usergroup_user_group_id_get

        Get User Group
        """
        pass

    def test_get_user_groups_v1_usergroup_get(self) -> None:
        """Test case for get_user_groups_v1_usergroup_get

        Get User Groups
        """
        pass

    def test_patch_user_group_v1_usergroup_user_group_id_patch(self) -> None:
        """Test case for patch_user_group_v1_usergroup_user_group_id_patch

        Patch User Group
        """
        pass

    def test_post_user_group_pic_v1_usergroup_image_user_group_id_post(self) -> None:
        """Test case for post_user_group_pic_v1_usergroup_image_user_group_id_post

        Post User Group Pic
        """
        pass

    def test_post_user_group_v1_usergroup_post(self) -> None:
        """Test case for post_user_group_v1_usergroup_post

        Post User Group
        """
        pass


if __name__ == '__main__':
    unittest.main()
