# coding: utf-8

"""
    WeGlide

    Quantifying airsports

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from weglide_client.models.competition_in import CompetitionIn

class TestCompetitionIn(unittest.TestCase):
    """CompetitionIn unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CompetitionIn:
        """Test CompetitionIn
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CompetitionIn`
        """
        model = CompetitionIn()
        if include_optional:
            return CompetitionIn(
                name = '',
                description = '',
                url = '',
                logo = '',
                user_id = 56,
                strepla_id = 56,
                start = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                end = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                strepla_token = '',
                competition_class = [
                    weglide_client.models.competition_class_in.CompetitionClassIn(
                        name = '', 
                        device = [
                            weglide_client.models.competition_device_in.CompetitionDeviceIn(
                                id = '', 
                                index = 1.337, )
                            ], )
                    ]
            )
        else:
            return CompetitionIn(
                name = '',
                start = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                end = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                competition_class = [
                    weglide_client.models.competition_class_in.CompetitionClassIn(
                        name = '', 
                        device = [
                            weglide_client.models.competition_device_in.CompetitionDeviceIn(
                                id = '', 
                                index = 1.337, )
                            ], )
                    ],
        )
        """

    def testCompetitionIn(self):
        """Test CompetitionIn"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
