from typing import Optional, Tuple, Any

class PtyPopen:
    def __init__(self, args: list[str]) -> None: ...
    def wait(self, timeout: Optional[float] = None) -> int: ...
    def communicate(self, input: Optional[bytes] = None) -> Tuple[bytes, bytes]: ...
    def poll(self) -> Optional[int]: ...
    def kill(self) -> None: ...
    def terminate(self) -> None: ...
    def send_signal(self, signal: int) -> None: ...
    @property
    def pid(self) -> int: ...
    @property
    def returncode(self) -> int: ...