from enum import Enum

class Auto_Mode(Enum):
    disable = 0
    normal = 1
    high = 2
    highest = 3

def get_temp_path(relative_path: str = ''): ...
def getProjectPath(layer: int = 0, auto: Auto_Mode | int = ...) -> str: ...
def is_executable() -> bool: ...
def is_dir_exists(path: str) -> bool: ...
def is_file_exists(path: str) -> bool: ...
