# coding: utf-8

"""
Slurm REST API

API to access and control Slurm

The version of the OpenAPI document: Slurm-24.11.1&openapi/slurmdbd&openapi/slurmctld
Contact: sales@schedmd.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from slurmrestpy.models.v0042_assoc_default import V0042AssocDefault


class TestV0042AssocDefault(unittest.TestCase):
    """V0042AssocDefault unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0042AssocDefault:
        """Test V0042AssocDefault
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `V0042AssocDefault`
        """
        model = V0042AssocDefault()
        if include_optional:
            return V0042AssocDefault(
                qos = ''
            )
        else:
            return V0042AssocDefault(
        )
        """

    def testV0042AssocDefault(self):
        """Test V0042AssocDefault"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
