# coding: utf-8

"""
Slurm REST API

API to access and control Slurm

The version of the OpenAPI document: Slurm-24.11.1&openapi/slurmdbd&openapi/slurmctld
Contact: sales@schedmd.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from slurmrestpy.models.v0042_job_res_node_memory import V0042JobResNodeMemory


class TestV0042JobResNodeMemory(unittest.TestCase):
    """V0042JobResNodeMemory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0042JobResNodeMemory:
        """Test V0042JobResNodeMemory
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `V0042JobResNodeMemory`
        """
        model = V0042JobResNodeMemory()
        if include_optional:
            return V0042JobResNodeMemory(
                used = 56,
                allocated = 56
            )
        else:
            return V0042JobResNodeMemory(
        )
        """

    def testV0042JobResNodeMemory(self):
        """Test V0042JobResNodeMemory"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
