# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import typing
from ...types.api_key_request_list_response_data import ApiKeyRequestListResponseData
import pydantic
from .list_api_requests_params import ListApiRequestsParams
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class ListApiRequestsResponse(UniversalBaseModel):
    data: typing.List[ApiKeyRequestListResponseData] = pydantic.Field()
    """
    The returned resources
    """

    params: ListApiRequestsParams = pydantic.Field()
    """
    Input parameters
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
