# coding: utf-8

"""
    Curia Platform API

    These are the docs for the curia platform API. To test, generate an authorization token first.  # noqa: E501

    OpenAPI spec version: 3.2.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CreateProcessDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'project_id': 'str',
        'status': 'str',
        'analysis_id': 'str'
    }

    attribute_map = {
        'type': 'type',
        'project_id': 'projectId',
        'status': 'status',
        'analysis_id': 'analysisId'
    }

    def __init__(self, type=None, project_id=None, status=None, analysis_id=None):  # noqa: E501
        """CreateProcessDto - a model defined in Swagger"""  # noqa: E501
        self._type = None
        self._project_id = None
        self._status = None
        self._analysis_id = None
        self.discriminator = None
        self.type = type
        self.project_id = project_id
        if status is not None:
            self.status = status
        if analysis_id is not None:
            self.analysis_id = analysis_id

    @property
    def type(self):
        """Gets the type of this CreateProcessDto.  # noqa: E501


        :return: The type of this CreateProcessDto.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this CreateProcessDto.


        :param type: The type of this CreateProcessDto.  # noqa: E501
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501
        allowed_values = ["diagnosis_gaps_economic_evaluation", "build_cohort_dataset", "build_outcome_dataset", "build_intervention_dataset", "build_feature_dataset", "build_modeling_dataset"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def project_id(self):
        """Gets the project_id of this CreateProcessDto.  # noqa: E501


        :return: The project_id of this CreateProcessDto.  # noqa: E501
        :rtype: str
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id):
        """Sets the project_id of this CreateProcessDto.


        :param project_id: The project_id of this CreateProcessDto.  # noqa: E501
        :type: str
        """
        if project_id is None:
            raise ValueError("Invalid value for `project_id`, must not be `None`")  # noqa: E501

        self._project_id = project_id

    @property
    def status(self):
        """Gets the status of this CreateProcessDto.  # noqa: E501


        :return: The status of this CreateProcessDto.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this CreateProcessDto.


        :param status: The status of this CreateProcessDto.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def analysis_id(self):
        """Gets the analysis_id of this CreateProcessDto.  # noqa: E501


        :return: The analysis_id of this CreateProcessDto.  # noqa: E501
        :rtype: str
        """
        return self._analysis_id

    @analysis_id.setter
    def analysis_id(self, analysis_id):
        """Sets the analysis_id of this CreateProcessDto.


        :param analysis_id: The analysis_id of this CreateProcessDto.  # noqa: E501
        :type: str
        """

        self._analysis_id = analysis_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CreateProcessDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateProcessDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
