def get_file_bom(file_path): ...
def get_file_encoding(file_path, candidate_encodings=['utf-8', 'gbk', 'iso-8859-9']): ...
def get_file_content(file_path, candidate_encodings=['utf-8', 'gbk', 'iso-8859-9']): ...
