# coding: utf-8

"""
    Curia Platform API

    These are the docs for the curia platform API. To test, generate an authorization token first.  # noqa: E501

    OpenAPI spec version: 3.4.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import curia.api.curia.api.curia.api.curia.api.swagger_client
from curia.api.curia.api.curia.api.curia.api.swagger_client.models.get_many_data_store_response_dto import GetManyDataStoreResponseDto  # noqa: E501
from curia.api.curia.api.curia.api.curia.api.swagger_client.rest import ApiException


class TestGetManyDataStoreResponseDto(unittest.TestCase):
    """GetManyDataStoreResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetManyDataStoreResponseDto(self):
        """Test GetManyDataStoreResponseDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = curia.api.curia.api.curia.api.swagger_client.models.get_many_data_store_response_dto.GetManyDataStoreResponseDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
