from ctypes import *
from ..n_common.u_io import get_temp_path as get_temp_path

class c_libs:
    def __init__(self) -> None: ...
    def start_tmdprotect(self) -> None: ...
    def end_tmdprotect(self) -> None: ...
    def testfunc1(self) -> None: ...
    def mys_sum(self, a: int, b: int) -> int: ...
