# coding: utf-8

"""
    Curia Platform API

    These are the docs for the curia platform API. To test, generate an authorization token first.  # noqa: E501

    OpenAPI spec version: 2.14.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import curia.api.curia.api.curia.api.curia.api.swagger_client
from curia.api.curia.api.curia.api.curia.api.swagger_client.api.analysis_jobs_api import AnalysisJobsApi  # noqa: E501
from curia.api.curia.api.curia.api.curia.api.swagger_client.rest import ApiException


class TestAnalysisJobsApi(unittest.TestCase):
    """AnalysisJobsApi unit test stubs"""

    def setUp(self):
        self.api = AnalysisJobsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_analysis_job_controller_start(self):
        """Test case for analysis_job_controller_start

        Start analysis job  # noqa: E501
        """
        pass

    def test_analysis_job_controller_stop(self):
        """Test case for analysis_job_controller_stop

        Stop analysis job  # noqa: E501
        """
        pass

    def test_create_many_base_analysis_job_controller_analysis_job(self):
        """Test case for create_many_base_analysis_job_controller_analysis_job

        Create many AnalysisJob  # noqa: E501
        """
        pass

    def test_create_one_base_analysis_job_controller_analysis_job(self):
        """Test case for create_one_base_analysis_job_controller_analysis_job

        Create one AnalysisJob  # noqa: E501
        """
        pass

    def test_delete_one_base_analysis_job_controller_analysis_job(self):
        """Test case for delete_one_base_analysis_job_controller_analysis_job

        Delete one AnalysisJob  # noqa: E501
        """
        pass

    def test_get_many_base_analysis_job_controller_analysis_job(self):
        """Test case for get_many_base_analysis_job_controller_analysis_job

        Retrieve many AnalysisJob  # noqa: E501
        """
        pass

    def test_get_one_base_analysis_job_controller_analysis_job(self):
        """Test case for get_one_base_analysis_job_controller_analysis_job

        Retrieve one AnalysisJob  # noqa: E501
        """
        pass

    def test_replace_one_base_analysis_job_controller_analysis_job(self):
        """Test case for replace_one_base_analysis_job_controller_analysis_job

        Replace one AnalysisJob  # noqa: E501
        """
        pass

    def test_update_one_base_analysis_job_controller_analysis_job(self):
        """Test case for update_one_base_analysis_job_controller_analysis_job

        Update one AnalysisJob  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
