#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2501-24-g12ef984e"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2501
#define NETGEN_VERSION_TWEAK 24
#define NETGEN_VERSION_HASH "g12ef984e"
#endif // NETGEN_VERSION_HPP_INCLUDED
