class YJKSControl:
    @staticmethod
    def init(yjkPath: str, Version: str) -> str: ...
    @staticmethod
    def exit() -> None: ...
    @staticmethod
    def RunCmd(strScriptKeyWord: str, para1: str, para2: str) -> None: ...
    @staticmethod
    def RunCmd(strScriptKeyWord: str, strParameter: str) -> None: ...