from zodable_sample_package.digital.guimauve.example.Address import AddressSchema
from zodable_sample_package.digital.guimauve.example.Country import CountrySchema
from zodable_sample_package.digital.guimauve.example.User import UserSchema
